<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Comun\Comun.csproj" />
    <ProjectReference Include="..\Datos\Datos.csproj" />
    <ProjectReference Include="..\Servicios\Servicios.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Dapper.Oracle" Version="2.0.2" />
    <PackageReference Include="Otp.NET" Version="1.4.1" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
  </ItemGroup>

</Project>
