<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Comun\Comun.csproj" />
    <ProjectReference Include="..\Datos\Datos.csproj" />
    <ProjectReference Include="..\Servicios\Servicios.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Gestion\Listas\" />
    <Folder Include="Gestion\Reportes\" />
    <Folder Include="Interfaz\Listas\" />
    <Folder Include="Interfaz\Reportes\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Dapper.Oracle" Version="2.0.2" />
  </ItemGroup>

</Project>
